spring:
  application:
    name: zyplayer-doc-manage
#  mvc:
#    static-path-pattern: /**

server:
  port: 8082
  servlet:
    context-path: /zyplayer-doc-manage

zyplayer:
  doc:
    # dubbo相关配置
    dubbo:
      # 优先使用zookeeper，未配置时找nacos的配置
      zookeeper:
#        url: 127.0.0.1:2181
      nacos:
#        url: http://127.0.0.1:8848/nacos
        # 服务名称，多个使用 ; 分割，nacos没办法获取所有的服务列表，所以需要指定
        service: "com.zyplayer.dubbo.service.UserService;\
                  com.zyplayer.dubbo.service.AnnotateService;"
    # swagger相关配置
    swagger:
      proxy-request:
        # 允许代理请求的域名，正则表达式，多个使用 ; 分割，必须设置，防止通过代理接口访问到内部资源，实在觉得没必要可设置为：.+
        white-domain: \S+\.zyplayer\.com;127.0.1:8080;\S+\.xiaominfo\.com;
    # zyplayer_doc_manage管理端的数据库配置
    manage:
      datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/zyplayer_doc_manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
        username: root
        password: root
      # 通过nginx代理之后没端口，但tomcat容器有端口，spring security会判断如果是http开头的则直接跳
      # 如果你也遇到了这个问题，可以把登陆地址写成http://开头的一个地址
      login-page: /static/manage/login.html
    # 数据库文档相关
    # 打开/zyplayer_doc_manage/doc-db.html即可看到这里配置的数据库的文档
    db:
      dbConfigList:
        - driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/zyplayer_doc_manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
          username: root
          password: root
        # 多个数据源直接这样累加
#        - driverClassName: com.mysql.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/zyplayer_doc_manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
#          username: root
#          password: root

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zyplayer.doc.manage.repository.manage.entity
  typeEnumsPackage:
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


#一些测试地址
#https://gitee.com/GeekPerson/central-platform 项目的文档
#http://47.99.88.28:9200/swagger-resources
