spring:
  application:
    name: zyplayer-doc-manage
  velocity:
    layout-url: common/default.vm
    cache: false
    suffix: .vm
    expose-spring-macro-helpers: true
    date-tool-attribute: dateTool
    number-tool-attribute: numberTool
    contentType: text/html;charset=UTF-8
    resource-loader-path: classpath:/vm/
    default-content-type: text/html
    ignore-accept-header: true
    charset: UTF-8
    properties:
      input:
        encoding: UTF-8
      output:
        encoding: UTF-8

server:
  port: 8082
  servlet:
    context-path: /zyplayer-doc-manage


zyplayer:
  doc:
    # zyplayer-doc-manage管理端的数据库配置
    manage:
      datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/zyplayer-doc-manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
        username: root
        password: root
    # 数据库文档相关
    # 打开/zyplayer-doc-manage/doc-db.html即可看到这里配置的数据库的文档
    db:
      dbConfigList:
        - driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/zyplayer-doc-manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
          username: root
          password: root
        # 多个数据源直接这样累加
#        - driverClassName: com.mysql.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/zyplayer-doc-manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
#          username: root
#          password: root

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.baomidou.springboot.entity
  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  
  
#一些测试地址
#https://gitee.com/GeekPerson/central-platform 项目的文档
#http://47.99.88.28:9200/swagger-resources